version: "3.8"
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.3.1
    restart: on-failure:3
    links:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ADVERTISED_PORT: '9092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_MESSAGE_MAX_BYTES: '200000000'
      KAFKA_VERSION: '2.3.1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
